### ISSUE TITLE
Is it possible to pass variables into Hues.huestr() as arguments?

### ISSUE THREAD

**Issue by campbellized** [prashnts/hues#3]
In the documentation I saw that you had the example:

`print(hues.huestr(' 42 ').white.bg_blue.bold.colorized)`

Is it possible to pass a variable into Hues.huestr()? I would like to be able to assign a color to a variable and then print. I'm trying to do something like this:

```
color = "cyan"
print(hues.huestr('This text should be in color.', color))
```
I'm not getting any errors, but I haven't been able to get the text to print out in color.

Thanks!

**Comment by prashnts** [comment]
Currently the api for passing variables to `Huestr` is really awkward. (You can help decide how it should be!) Anyway, a couple of things needed here:

`color = "cyan"` won't work: it needs to resolve to `ANSI` color. The color codes are in the `hues.colortable` module. Try this out:

```python
import hues
color = hues.colortable.FG.cyan     # or, use getattr(hues.colortable.FG, "cyan")`
print(hues.huestr('This text should be in color.', hue_stack=(color,))
```

Notice `hue_stack` is a `tuple`.

That said, I _do_ plan to figure out a "natural" `API` for this.

**Comment by campbellized** [comment]
After looking at `hues.colortable` I feel like I have a better understanding of ANSI color codes. I modified my program to assign an integer representing an ANSI color code instead of a string. It's working great. I'm now doing something like this:

```
import hues
color = 36 # ANSI foreground color Cyan
print(hues.huestr("This text should be cyan.", hue_stack=(color,)).colorized)
```

Thanks for your help! I will keep an eye on this repo and try and see if I can be of any assistance.
